# Generated by Django 5.0.2 on 2024-02-12 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studies', '0005_alter_subject_study'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localtime', models.DateTimeField()),
                ('servertime', models.DateTimeField()),
                ('behavior', models.CharField(max_length=200)),
                ('affect', models.CharField(max_length=200)),
                ('intervention', models.CharField(max_length=200)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studies.subject')),
            ],
        ),
    ]
