# Generated by Django 5.0.2 on 2024-02-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='marked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='note',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
