# Generated by Django 5.0.2 on 2024-02-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_record_marked_record_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='exclude',
            field=models.BooleanField(default=False),
        ),
    ]
