# Generated by Django 5.0.2 on 2024-02-11 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('software', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('trail', models.CharField(max_length=200)),
                ('behavior', models.CharField(max_length=200)),
                ('affect', models.CharField(max_length=200)),
                ('localtime', models.DateTimeField()),
                ('servertime', models.DateTimeField()),
                ('intervention', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('label', models.CharField(max_length=200)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studies.study')),
            ],
        ),
    ]
