# Generated by Django 5.0.2 on 2024-02-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_rename_subjects_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='localtime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='servertime',
            field=models.DateTimeField(null=True),
        ),
    ]
