# Generated by Django 5.0.2 on 2024-02-12 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0004_study_localendtime_study_serverendtime_study_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studies.study'),
        ),
    ]
