# Generated by Django 4.2.4 on 2024-02-21 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0005_alter_subject_study'),
    ]

    operations = [
        migrations.RenameField(
            model_name='study',
            old_name='trail',
            new_name='trial',
        ),
    ]
